services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped

    ports:
      - "27017:27017"

    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

    command: >
      mongod
        --auth
        --bind_ip 0.0.0.0

    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./certs:/etc/ssl
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    restart: unless-stopped

    # forwarded out only to 127.0.0.1
    ports:
      - "127.0.0.1:6379:6379"

    env_file: .env
    command: >
      redis-server
        --requirepass ${REDIS_PASSWORD}
        --rename-command CONFIG ""
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  token-indexer:
    build:
      context: .
      network: host
    env_file: .env
    depends_on:
      - mongo
      - redis
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped

volumes:
  mongo-data:
